from almondegas import Test

contrato_obrigatorio = {
    "tipo",
    "id_cliente",
    "id_vd_contrato",
    "contrato",
    "id_tipo_contrato",
    "id_modelo",
    "id_filial",
    "data",
    "id_tipo_documento",
    "id_carteira_cobranca",
    "id_vendedor",
    "cc_previsao",
    "tipo_cobranca",
    "renovacao_automatica",
    "base_geracao_tipo_doc",
    "bloqueio_automatico",
    "aviso_atraso",
    "endereco_padrao_cliente",
}

contrato_obrigatorio_e_datas = {
    "tipo",
    "id_cliente",
    "id_vd_contrato",
    "contrato",
    "id_tipo_contrato",
    "id_modelo",
    "id_filial",
    "data",
    "id_tipo_documento",
    "id_carteira_cobranca",
    "id_vendedor",
    "cc_previsao",
    "tipo_cobranca",
    "renovacao_automatica",
    "base_geracao_tipo_doc",
    "bloqueio_automatico",
    "aviso_atraso",
    "endereco_padrao_cliente",
    "data_assinatura",
    "data_ativacao",
    "data_renovacao",
    "pago_ate_data",
    "data_expiracao",
    "dica_data_expiracao",
    "data_inicial_suspencao",
    "data_final_suspencao",
    "data_acesso_desativado",
    "data_cancelamento",
    "data_negativacao",
    "data_desistencia",
    "data_cadastro_sistema",
    "data_retomada_sistema",
}

contrato_defaults = {
    "tipo": "I",
    "id_cliente": "",
    "id_vd_contrato": "",
    "descricao_aux_plano_venda": "",
    "contrato": "",
    "id_tipo_contrato": "",
    "id_modelo": "",
    "assinatura_digital": "P",
    "integracao_assinatura_digital": "P",
    "liberacao_bloqueio_manual": "P",
    "id_filial": "",
    "indicacao_contrato_id": "",
    "data_assinatura": "",
    "isentar_contrato": "S",
    "data_ativacao": "",
    "data": "",
    "data_renovacao": "",
    "pago_ate_data": "",
    "status": "P",
    "status_internet": "D",
    "status_velocidade": "N",
    "tipo_produtos_plano": "P",
    "motivo_inclusao": "I",
    "id_indexador_reajuste": "",
    "url_assinatura_digital": "",
    "token_assinatura_digital": "",
    "id_tipo_documento": "",
    "id_carteira_cobranca": "",
    "id_vendedor": "",
    "moeda": "",
    "comissao": "",
    "cc_previsao": "P",
    "tipo_cobranca": "P",
    "renovacao_automatica": "S",
    "gerar_finan_assin_digital_contrato": "P",
    "base_geracao_tipo_doc": "P",
    "id_contrato_principal": "",
    "num_parcelas_atraso": "",
    "nf_info_adicionais": "",
    "credit_card_recorrente_bandeira_cartao": "",
    "credit_card_recorrente_token": "",
    "ids_contratos_recorrencia": "",
    "tipo_doc_opc": "",
    "tipo_doc_opc2": "",
    "tipo_doc_opc3": "",
    "tipo_doc_opc4": "",
    "id_tipo_doc_ativ": "",
    "id_produto_ativ": "",
    "taxa_instalacao": "0.00",
    "id_cond_pag_ativ": "",
    "id_responsavel": "",
    "id_vendedor_ativ": "",
    "ativacao_numero_parcelas": "",
    "ativacao_vencimentos": "",
    "btn_nf_ativacao": "",
    "ativacao_valor_parcela": "",
    "fidelidade": "",
    "data_expiracao": "",
    "dica_data_expiracao": "",
    "desconto_fidelidade": "0.00",
    "id_instalador": "",
    "taxa_improdutiva": "",
    "venc_personalizado": "",
    "com_entrada": "",
    "dia_fixo_vencimento": "",
    "tipo_condicao_pag": "",
    "bloqueio_automatico": "S",
    "nao_bloquear_ate": "",
    "aviso_atraso": "S",
    "nao_avisar_ate": "",
    "desbloqueio_confianca": "P",
    "desbloqueio_confianca_ativo": "N",
    "restricao_auto_desbloqueio": "N",
    "motivo_restricao_auto_desbloq": "",
    "obs": "",
    "nao_susp_parc_ate": "",
    "liberacao_suspensao_parcial": "P",
    "utilizando_auto_libera_susp_parc": "N",
    "restricao_auto_libera_susp_parcial": "N",
    "motivo_restri_auto_libera_parc": "",
    "contrato_suspenso": "N",
    "data_inicial_suspensao": "",
    "data_final_suspensao": "",
    "data_acesso_desativado": "",
    "data_cancelamento": "",
    "id_responsavel_cancelamento": "",
    "motivo_cancelamento": "",
    "motivo_adicional": "",
    "concorrente_mot_adicional": "",
    "dica_motivo_adicional_cliente_contrato": "",
    "obs_cancelamento": "",
    "data_negativacao": "",
    "id_responsavel_negativacao": "",
    "protocolo_negativacao": "",
    "id_motivo_negativacao": "",
    "obs_negativacao": "",
    "data_desistencia": "",
    "id_responsavel_desistencia": "",
    "motivo_desistencia": "",
    "obs_desistencia": "",
    "obs_contrato": "",
    "alerta_contrato": "",
    "imp_realizado": "S",
    "imp_inicial": "",
    "imp_carteira": "N",
    "imp_importacao": "N",
    "imp_treinamento": "N",
    "imp_rede": "N",
    "imp_bkp": "N",
    "imp_obs": "",
    "imp_final": "",
    "imp_status": "A",
    "imp_motivo": "",
    "dt_ult_bloq_auto": "",
    "dt_ult_bloq_manual": "",
    "dt_ult_finan_atraso": "",
    "dt_ult_des_bloq_conf": "",
    "dt_ult_liberacao_susp_parc": "",
    "dt_ult_ativacao": "",
    "dt_utl_negativacao": "",
    "dt_ult_desiste": "",
    "data_cadastro_sistema": "",
    "ultima_atualizacao": "CURRENT_TIMESTAMP",
    "data_retomada_contrato": "NULL",
    "endereco_padrao_cliente": "S",
    "endereco_padrao_alert": "",
    "id_condominio": "",
    "condominio_novo": "",
    "bloco": "",
    "bloco_novo": "",
    "apartamento": "",
    "apartamento_novo": "",
    "cep": "",
    "cep_novo": "",
    "endereco": "",
    "endereco_novo": "",
    "numero": "",
    "numero_novo": "",
    "bairro": "",
    "bairro_novo": "",
    "cidade": "",
    "cidade_novo": "",
    "complemento": "",
    "complemento_novo": "",
    "referencia": "",
    "referencia_novo": "",
    "latitude": "",
    "latitude_novo": "",
    "longitude": "",
    "longitude_novo": "",
    "tipo_localidade": "U",
    "avalista_1": "",
    "avalista_2": "",
    "testemunha_assinatura_digital": "",
    "document_photo": "P",
    "selfie_photo": "P"
}

contrato_campos = {
	"tipo",
	"id_cliente",
	"id_vd_contrato",
	"descricao_aux_plano_venda",
	"contrato",
	"id_tipo_contrato",
	"id_modelo",
	"assinatura_digital",
	"integracao_assinatura_digital",
	"liberacao_bloqueio_manual",
	"id_filial",
	"indicacao_contrato_id",
	"data_assinatura",
	"isentar_contrato",
	"data_ativacao",
	"data",
	"data_renovacao",
	"pago_ate_data",
	"status",
	"status_internet",
	"status_velocidade",
	"tipo_produtos_plano",
	"motivo_inclusao",
	"id_indexador_reajuste",
	"url_assinatura_digital",
	"token_assinatura_digital",
	"id_tipo_documento",
	"id_carteira_cobranca",
	"id_vendedor",
	"moeda",
	"comissao",
	"cc_previsao",
	"tipo_cobranca",
	"renovacao_automatica",
	"gerar_finan_assin_digital_contrato",
	"base_geracao_tipo_doc",
	"id_contrato_principal",
	"num_parcelas_atraso",
	"nf_info_adicionais",
	"credit_card_recorrente_bandeira_cartao",
	"credit_card_recorrente_token",
	"ids_contratos_recorrencia",
	"tipo_doc_opc",
	"tipo_doc_opc2",
	"tipo_doc_opc3",
	"tipo_doc_opc4",
	"id_tipo_doc_ativ",
	"id_produto_ativ",
	"taxa_instalacao",
	"id_cond_pag_ativ",
	"id_responsavel",
	"id_vendedor_ativ",
	"ativacao_numero_parcelas",
	"ativacao_vencimentos",
	"ativacao_valor_parcela",
	"fidelidade",
	"data_expiracao",
	"desconto_fidelidade",
	"id_instalador",
	"taxa_improdutiva",
	"tipo_condicao_pag",
	"bloqueio_automatico",
	"nao_bloquear_ate",
	"aviso_atraso",
	"nao_avisar_ate",
	"desbloqueio_confianca",
	"desbloqueio_confianca_ativo",
	"restricao_auto_desbloqueio",
	"motivo_restricao_auto_desbloq",
	"obs",
	"nao_susp_parc_ate",
	"liberacao_suspensao_parcial",
	"utilizando_auto_libera_susp_parc",
	"restricao_auto_libera_susp_parcial",
	"motivo_restri_auto_libera_parc",
	"contrato_suspenso",
	"data_inicial_suspensao",
	"data_final_suspensao",
	"data_acesso_desativado",
	"data_cancelamento",
	"id_responsavel_cancelamento",
	"motivo_cancelamento",
	"motivo_adicional",
	"concorrente_mot_adicional",
	"obs_cancelamento",
	"data_negativacao",
	"id_responsavel_negativacao",
	"protocolo_negativacao",
	"id_motivo_negativacao",
	"obs_negativacao",
	"data_desistencia",
	"id_responsavel_desistencia",
	"motivo_desistencia",
	"obs_desistencia",
	"obs_contrato",
	"alerta_contrato",
	"imp_realizado",
	"imp_inicial",
	"imp_carteira",
	"imp_importacao",
	"imp_treinamento",
	"imp_rede",
	"imp_bkp",
	"imp_obs",
	"imp_final",
	"imp_status",
	"imp_motivo",
	"dt_ult_bloq_auto",
	"dt_ult_finan_atraso",
	"dt_ult_des_bloq_conf",
	"dt_ult_liberacao_susp_parc",
	"dt_ult_ativacao",
	"dt_utl_negativacao",
	"dt_ult_desiste",
	"data_cadastro_sistema",
	"ultima_atualizacao",
	"data_retomada_contrato",
	"endereco_padrao_cliente",
	"id_condominio",
	"bloco",
	"apartamento",
	"cep",
	"endereco",
	"numero",
	"bairro",
	"cidade",
	"complemento",
	"referencia",
	"latitude",
	"longitude",
	"tipo_localidade",
	"avalista_1",
	"avalista_2",
	"testemunha_assinatura_digital",
	"document_photo",
	"selfie_photo",
}

if __name__ == "__main__":
    teste = Test("cliente", "4")

    print("testando repor normalizado")
    print("--")
    teste.update(teste.fetched[0])
    teste.isequal()

    print("testando campos obrigatórios conforme documentação")
    print("--")
    obj = teste.filter(contrato_obrigatorio)
    print(obj)
    teste.update(obj)
    teste.isequal()


    print("testando campos obrigatórios com datas")
    print("--")
    obj = teste.filter(contrato_obrigatorio_e_datas)
    print(obj)
    teste.update(obj)
    teste.isequal()

    print("testando pôr valores padrão")
    print("--")
    teste.update(contrato_defaults)
    teste.isequal()

    print("testando pôr com os principais campos")
    print("--")
    teste.update(teste.filter(contrato_campos))
    teste.isequal()

    print("repôndo valores prévios")
    print("--")
    teste.undo()
